server:
  port: 8080
spring:
  application:
    name: otus-x
  datasource:
    write:
      platform: postgres
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5431/otus_x
      username: otus_x
      password: otus_x
      liquibase:
        changeLog: "classpath:db/changelog/changelog.xml"
        default-schema: "public"
    read:
      platform: postgres
      driverClassName: org.postgresql.Driver
      url: jdbc:postgresql://localhost:62277/otus_x
      username: otus_x
      password: otus_x
  data:
    redis:
      host: localhost
      port: 6379
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbit
    password: rabbit
  scheduler:
    newsfeed-rate: 3600000
rabbitmq:
  exchange: newsfeed
  queue: newsfeed
  ws:
    relay-host: localhost
    relay-port: 61613
    messages: /post/feed/posted
    subscriptions: subscriptions
otus-x:
  token:
    key: b3R1c194X3NlY3JldF9rZXlfZm9yX2p3dC1vdHVzLWhvbWV0YXNrLTAxLXNob3VsZC1iZS1kb25l
    expiration-in-minutes: 1440
management:
  tracing:
    sampling:
      probability: 1.0