services:
  web:
    image: nginx
    restart: on-failure
    volumes:
      - "./default.conf:/etc/nginx/conf.d/default.conf"
    ports:
      - "3654:80"
      - "3456:8080"
    environment:
      - NGINX_HOST=foobar.com
      - NGINX_PORT=80
  haproxy:
    image: haproxy:2.9.7
    restart: unless-stopped
    volumes:
      - "./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
  postgresql-leader:
    image: docker.io/bitnami/postgresql:16
    container_name: leader
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=otus_x
      - POSTGRESQL_PASSWORD=otus_x
      - POSTGRESQL_DATABASE=otus_x
      - ALLOW_EMPTY_PASSWORD=yes
  postgresql-follower-1:
    image: docker.io/bitnami/postgresql:16
    container_name: postgresql-follower-1
    depends_on:
      - postgresql-leader
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgresql-leader
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - ALLOW_EMPTY_PASSWORD=yes
  postgresql-follower-2:
    image: docker.io/bitnami/postgresql:16
    container_name: postgresql-follower-2
    depends_on:
      - postgresql-leader
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgresql-leader
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
      - ALLOW_EMPTY_PASSWORD=yes
  user-service:
    image: kurov1993/otus-x:0.2
    deploy:
      replicas: 3
    depends_on:
      - postgresql-follower-1
      - postgresql-follower-2
      - web
    environment:
      SPRING_DATASOURCE_WRITE_URL: jdbc:postgresql://haproxy:5432/otus_x
      SPRING_DATASOURCE_READ_URL: jdbc:postgresql://haproxy:5433/otus_x
      MANAGEMENT_ZIPKIN_TRACING_ENDPOINT: http://zipkin:9411/api/v2/spans
volumes:
  postgresql_master_data:
    driver: local